---
- hosts: test
  remote_user: root
  vars:
    user1: iakim
    user2: iakim2
    user3: isaac

  tasks:
  - name: Remove user1
    user: name={{ user1 }} state=absent

  - name: Deleting the home
    shell: rm -rf /home/{{ user1 }}

  - name: Remove user2
    user: name={{ user2 }} state=absent

  - name: Deleting the home
    shell: rm -rf /home/{{ user2 }}

  - name: Remove user3
    user: name={{ user3 }} state=absent

  - name: Deleting the home
    shell: rm -rf /home/{{ user3 }}
